const restaurants = [
    {
        id: '1',
        name: 'Phở Hòa',
        tags: ['Phở'],
        rating: 4.7,
        distance: 3.2,
        deliveryTime: 40,
        reviewCount: 527,
        image: require('../assets/images/pho-hoa.jpg'),
    },
    {
        id: '2',
        name: 'Bún chả Hương Liên',
        tags: ['Bún chả'],
        rating: 4.5,
        distance: 2.5,
        deliveryTime: 35,
        reviewCount: 408,
        image: require('../assets/images/bun-cha-huong-lien.jpg'),
    },
    {
        id: '3',
        name: 'Bánh xèo 46A',
        tags: ['Bánh xèo'],
        rating: 4.2,
        distance: 1.8,
        deliveryTime: 25,
        reviewCount: 292,
        image: require('../assets/images/banh-xeo-46A.jpg'),
    },
    {
        id: '4',
        name: 'Bánh mì Phượng',
        tags: ['Bánh mì'],
        rating: 4.4,
        distance: 1.2,
        deliveryTime: 20,
        reviewCount: 188,
        image: require('../assets/images/banh-mi-phuong.jpg'),
    },
    {
        id: '5',
        name: 'Cơm tấm Cali',
        tags: ['Cơm Tấm'],
        rating: 4.6,
        distance: 2.0,
        deliveryTime: 30,
        reviewCount: 1273,
        image: require('../assets/images/com-tam-cali.jpg'),
    },
    {
        id: '6',
        name: 'Chả cá Lã Vọng',
        tags: ['Chả cá'],
        rating: 4.8,
        distance: 4.0,
        deliveryTime: 50,
        reviewCount: 1537,
        image: require('../assets/images/cha-ca-la-vong.jpg'),
    },
    {
        id: '7',
        name: 'Gỏi đu đủ Ty Thy',
        tags: ['Gỏi'],
        rating: 4.3,
        distance: 2.8,
        deliveryTime: 35,
        reviewCount: 237,
        image: require('../assets/images/goi-du-du-ty-thy.jpg'),
    },
    {
        id: '8',
        name: 'Bún riêu cua Đông Ba',
        tags: ['Bún riêu'],
        rating: 4.5,
        distance: 3.5,
        deliveryTime: 45,
        reviewCount: 1477,
        image: require('../assets/images/bun-rieu-cua-dong-ba.jpg'),
    },
    {
        id: '9',
        name: 'Bánh cuốn Tây Hồ',
        tags: ['Bánh cuốn'],
        rating: 4.2,
        distance: 2.3,
        deliveryTime: 30,
        reviewCount: 547,
        image: require('../assets/images/banh-cuon-tay-ho.jpg'),
    },
    {
        id: '10',
        name: 'Miến trộn Thanh Xuân',
        tags: ['Miến trộn'],
        rating: 4.0,
        distance: 2.2,
        deliveryTime: 25,
        reviewCount: 527,
        image: require('../assets/images/mien-tron-thanh-xuan.jpg'),
    },
];
export default restaurants;